equinor/mad

- .github/workflows/release.yml
- Add emojis to workflow steps
- Add dummy release step
- Add PR title and commit message template for release bot
> chore: format release workflow

- .changeset/unlucky-snakes-heal.md
- apps/chronicles/screens/components/PopoverScreen.tsx
- packages/components/src/components/Popover/Popover.tsx
> feat: rounded arrow

- .changeset/little-ravens-beg.md
- apps/chronicles/metro.config.js
- apps/chronicles/package.json
- pnpm-lock.yaml
- Refresh package lock
- fix metro config package linking
- pin SKIA to hard version
> fix: dependencies

- .changeset/gentle-apples-fly.md
- .github/workflows/release.yml
- .prettierrc
- README.md
- apps/chronicles/package.json
- package.json
- packages/components/package.json
- packages/components/src/hooks/useDynamicStyle.ts
- packages/components/src/hooks/useEDS.ts
- packages/components/src/index.ts
- packages/components/src/types.d.ts
- packages/components/tsconfig.json
- packages/components/tsup.config.ts
- packages/skia-draw/package.json
- packages/skia-draw/tsconfig.json
- packages/skia-draw/tsup.config.ts
- pnpm-lock.yaml
- Set up scripts for publishing packages
- Set up build scripts for mad components and skia-draw
- Repository docs
> feat: setup build system

- apps/chronicles/package.json
- package.json
- packages/components/src/hooks/useToken.ts
- pnpm-lock.yaml
- Remove not needed throw
closes #68
> fix: support packages not initializing provider

- apps/chronicles/package.json
- apps/chronicles/screens/components/PopoverScreen.tsx
- package.json
- packages/components/src/components/Button/ToggleButton/ToggleButton.tsx
- packages/eslint-config-mad-custom/package.json
- pnpm-lock.yaml
All linting tasks are successful now
> fix: eslint dependencies

- .changeset/tall-beans-eat.md
- apps/chronicles/navigation/index.tsx
- apps/chronicles/screens/DiscoverScreen.tsx
- apps/chronicles/screens/IconsScreen.tsx
- apps/chronicles/screens/components/AccordionScreen.tsx
- apps/chronicles/screens/components/CellScreen.tsx
- apps/chronicles/screens/components/NavigationCellScreen.tsx
- apps/chronicles/types.tsx
- packages/components/src/components/Accordion/Accordion.tsx
- packages/components/src/components/Accordion/AccordionItem.tsx
- packages/components/src/components/Accordion/index.ts
- packages/components/src/components/Cell/Cell.tsx
- packages/components/src/components/Cell/CellGroup.tsx
- packages/components/src/components/Cell/NavigationCell.tsx
- packages/components/src/index.ts
- packages/components/src/styling/masterToken.ts
- packages/components/src/styling/types.ts
- Add Accordion component in mad components
- Add AccordionScreen to chronicles
> feat: Accordion and AccordionItem

- .changeset/heavy-chefs-punch.md
- packages/components/src/components/Menu/Menu.tsx
- packages/components/src/components/PressableHighlight/PressableHighlight.tsx
- Animate `PressableHighlight` on release
- Remove dead style value
> feat: animated `PressableHighlight`

- .changeset/dull-waves-film.md
- apps/chronicles/screens/components/InputScreen.tsx
- apps/chronicles/screens/components/TextFieldScreen.tsx
- packages/components/src/components/Input/Input.tsx
- packages/components/src/components/Label/Label.tsx
- packages/components/src/components/TextField/TextField.tsx
- packages/components/src/styling/masterToken.ts
- packages/components/src/styling/types.ts
- Restructure and streamline text inputs
closes #90
> fix: text input styling and structure

- .changeset/curly-olives-admire.md
- .changeset/kind-items-carry.md
- .changeset/modern-rocks-flow.md
- .changeset/twelve-ducks-yell.md
- .changeset/wise-bears-laugh.md
- apps/chronicles/screens/components/ButtonScreen.tsx
- apps/chronicles/screens/components/PopoverScreen.tsx
- packages/components/src/components/Button/Button.tsx
- packages/components/src/components/Button/ButtonGroup.tsx
- packages/components/src/components/Button/ButtonGroup/ButtonGroup.tsx
- packages/components/src/components/Button/ButtonGroup/index.ts
- packages/components/src/components/Button/IconButton.tsx
- packages/components/src/components/Button/ToggleButton.tsx
- packages/components/src/components/Button/ToggleButton/index.ts
- packages/components/src/components/Button/index.ts
- packages/components/src/components/PressableHighlight/PressableHighlight.tsx
- packages/components/src/styling/masterToken.ts
- packages/components/src/styling/types.ts
- Refactor button component family
- Add icon support for text-labeled buttons
- Add `Button.Icon` component
closes #89
> feat: Icon button

- .changeset/silly-spies-fail.md
- apps/chronicles/screens/components/AccordionScreen.tsx
- packages/components/src/components/Accordion/AccordionItem.tsx
- Add support for `iconName` and `adornment` to `Accordion.Item`
> feat: accordion adornments

- .changeset/orange-birds-sing.md
- apps/chronicles/screens/components/TextFieldScreen.tsx
- packages/components/src/components/Input/Input.tsx
- Add `meta` prop to `Input` and `TextField` components
- Investigate onBlur behavior for input components
closes #99
> fix: textfield adjustments

- .changeset/funny-chicken-teach.md
- .changeset/hot-mice-smell.md
- .changeset/old-cycles-own.md
- .changeset/twenty-plants-attack.md
- .changeset/wet-clocks-tie.md
- apps/chronicles/navigation/index.tsx
- apps/chronicles/package.json
- apps/chronicles/screens/DiscoverScreen.tsx
- apps/chronicles/screens/components/ButtonScreen.tsx
- apps/chronicles/screens/components/ProgressIndicatorScreen.tsx
- apps/chronicles/types.tsx
- package.json
- packages/components/README.md
- packages/components/package.json
- packages/components/src/components/Button/Button.tsx
- packages/components/src/components/ProgressIndicator/CircularProgress.tsx
- packages/components/src/components/ProgressIndicator/DotProgress.tsx
- packages/components/src/components/ProgressIndicator/LinearProgress.tsx
- packages/components/src/components/ProgressIndicator/index.ts
- packages/components/src/components/ProgressIndicator/types.ts
- packages/components/src/components/ProgressIndicator/useAnimatedProgress.ts
- packages/components/src/components/ProgressIndicator/useNoProgressAnimation.ts
- packages/components/src/components/Typography/Typography.tsx
- packages/components/src/hooks/useToken.ts
- packages/components/src/index.ts
- pnpm-lock.yaml
- Add `CircularProgress`, `LinearProgress` and `DotProgress` indicators
- Add `loading` prop to `Button` component
closes #101
> feat: add progress indicators

- .changeset/spicy-frogs-exercise.md
- apps/chronicles/package.json
- apps/chronicles/screens/components/CellScreen.tsx
- apps/chronicles/screens/components/PopoverScreen.tsx
- package.json
- packages/components/src/components/Button/ButtonGroup.tsx
- packages/components/src/components/Cell/CellGroup.tsx
- packages/components/src/components/Cell/NavigationCell.tsx
- packages/components/src/components/Typography/Typography.tsx
- packages/components/src/hooks/useValidChildrenIndexes.ts
- packages/components/src/styling/types.ts
- packages/components/src/styling/utility.ts
- pnpm-lock.yaml
- Add `disabled` prop to `Cell.Navigation` component
- Style disabled navigation cells
- Fix bad validity check on cell group children
closes #106
> feat: add `disabled` prop to `Cell.Navigation` component

- .changeset/quiet-doors-look.md
- packages/components/src/components/Cell/CellGroup.tsx
- Add `adornment` prop to `Cell.Group` component
> feat: cell group adornment

- .changeset/hungry-bikes-add.md
- .vscode/settings.json
- apps/chronicles/screens/components/AccordionScreen.tsx
- packages/components/src/components/Accordion/AccordionItem.tsx
- Exclude all `**/dist` folders from vscode search
- Add `defaultOpen` prop to `Accordion.Item` component
- Remove strange line of code in `Accordion.Item` component
> feat: add `defaultOpen` prop to `Accordion.Item` component

- .changeset/stale-otters-search.md
- apps/chronicles/babel.config.js
- apps/chronicles/navigation/index.tsx
- apps/chronicles/package.json
- apps/chronicles/screens/components/CellScreen.tsx
- apps/chronicles/screens/components/NavigationCellScreen.tsx
- package.json
- packages/components/README.md
- packages/components/package.json
- packages/components/src/components/Cell/Cell.tsx
- packages/components/src/components/Cell/CellSwipeItem.tsx
- packages/components/src/components/Cell/NavigationCell.tsx
- packages/components/src/components/Cell/index.ts
- packages/components/src/components/Cell/types.ts
- pnpm-lock.yaml
> feat: add left and right swipe items for `Cell`

- .github/workflows/lint-pr.yml
> fix(CI): Add `--fix` option to lint step

- .github/workflows/lint-pr.yml
> fix: Lint CI checkout to new code

- .github/workflows/lint-pr.yml
- Add build stage to PR verification job
> chore(CI): add build step to PR validation

- packages/navigation/README.md
> chore: update readme with more info about environment provider

- packages/components/tsup.config.ts
Bundling = pain 😞🔫
^
||
v
No bundling = no pain
================ (to streka onda svaret)
> fix: don't bundle while in watch mode

- .changeset/small-cameras-tickle.md
- apps/chronicles/screens/LoginScreen.tsx
- apps/chronicles/screens/components/InputScreen.tsx
- apps/chronicles/screens/components/SearchScreen.tsx
- apps/chronicles/screens/components/TextFieldScreen.tsx
- packages/components/src/components/Button/IconButton.tsx
- packages/components/src/components/Input/Input.tsx
- packages/components/src/components/Search/Search.tsx
- Fixed a bug where the input was flickering when focused
- Added clear text button inside the search bar
- Added a optional cancel button next to search bar
Fixes: #207
> feat(search): update search bar 

- .changeset/late-planes-wait.md
- packages/components/src/components/Input/Input.tsx
- packages/components/src/components/Search/Search.tsx
- Using the search feature in another projects did not work well; the search bar became flat.
- Adjusted layout
> fix(search): correct search layout

- .changeset/late-planes-wait.md
- packages/components/src/components/Input/Input.tsx
- packages/components/src/components/Search/Search.tsx
> fix(search): Fix search field

- .changeset/perfect-poets-do.md
- packages/components/src/components/Input/Input.tsx
- packages/components/src/components/Search/Search.tsx
- Fixed clear text onchange inssues
- Fixed warnings
> fix(search): fix clear text onchange inssues

- .changeset/perfect-bobcats-give.md
- packages/components/src/components/Search/Search.tsx
- Make search get it's text from other sources. For example pressing a button adds text to the search field
> fix(search): make search get it's text from other sources

- .changeset/swift-countries-heal.md
- apps/chronicles/navigation/index.tsx
- apps/chronicles/screens/DiscoverScreen.tsx
- apps/chronicles/screens/components/AutocompleteScreen.tsx
- apps/chronicles/types.tsx
- packages/components/src/components/Autocomplete/Autocomplete.tsx
- packages/components/src/components/Autocomplete/index.ts
- packages/components/src/components/Input/Input.tsx
- packages/components/src/components/_internal/PopInContainer.tsx
- packages/components/src/index.ts
Add autocomplete component.
Changed inputprops.
> feat: add autocomplete

- SECURITY.md
> chore(repo): add compliance to policy for source code management scm system usage in equinor

- .changeset/little-icons-refuse.md
- packages/components/src/components/Autocomplete/Autocomplete.tsx
added flexGrow to `Autocomplete` `View` so that it is scalable
> fix: fixed autocomplete styling

- .changeset/slow-bags-smile.md
- apps/chronicles/screens/components/InputScreen.tsx
- apps/chronicles/screens/components/TextFieldScreen.tsx
- packages/components/src/components/Input/Input.tsx
- packages/components/src/components/TextField/TextField.tsx
- move props `label`,  `meta` and `helperText` from `Input` to `TextField`
- add `variant `prop to Input component
- add `helperIcon` and `inputIcon` to TextField
> feat: add variant prop to `Input`

- .changeset/quick-seas-vanish.md
- packages/components/src/components/Autocomplete/Autocomplete.tsx
Update `Autocomplete` to use `TextField` instead of `Input` component.
> refactor: change component import

- packages/auth/tsup.config.ts
- packages/components/tsup.config.ts
- packages/insights/tsup.config.ts
- packages/navigation/tsup.config.ts
- packages/skia-draw/tsup.config.ts
This will help us with pull request validation, and make the tsup configs simpler
> fix: `.d.ts` files are now created using tsup instead of tsc

- .changeset/curly-dodos-buy.md
- .changeset/strong-carpets-unite.md
- packages/components/src/components/Accordion/Accordion.tsx
- packages/components/src/components/Button/Button.tsx
- packages/components/src/components/Button/IconButton.tsx
- packages/components/src/components/TextField/TextField.tsx
- packages/components/src/styling/types.ts
- packages/components/src/styling/utility.ts
- packages/components/src/utils/getBackgroundColorForButton.ts
> fix: typescript errors in mad-components

- .changeset/tasty-glasses-play.md
- packages/components/src/components/Search/Search.tsx
Fixed the flex issues with Search. 
Key changes:
- changed input with textfield in search
- adjusted flex
Fixes: #260
> style(search): fix flex issues

- .changeset/purple-parents-visit.md
- packages/components/src/components/Typography/Typography.tsx
- packages/components/src/styling/masterToken.ts
- packages/components/src/styling/types.ts
Added Typography style for link as according to the EDS guidelines. Placed under group "interactive"
> feat: typography link style

- .changeset/happy-walls-live.md
- .changeset/nine-schools-jog.md
- .changeset/selfish-pots-leave.md
- apps/chronicles/components/GoToSettingsButton.tsx
- apps/chronicles/mad.config.ts
- apps/chronicles/navigation/SettingsScreen.tsx
- apps/chronicles/navigation/index.tsx
- packages/components/src/components/Cell/SwitchCell.tsx
- packages/components/src/components/Cell/index.ts
- packages/core/src/components/index.ts
- packages/core/src/components/screens/AboutScreen.tsx
- packages/core/src/components/screens/CreateIncidentScreen.tsx
- packages/core/src/components/screens/release-notes/ReleaseNotesScreen.tsx
- packages/core/src/components/screens/settings/Section.tsx
- packages/core/src/components/screens/settings/SettingsScreen.tsx
- packages/core/src/components/screens/settings/index.ts
- packages/core/src/components/screens/settings/renderCell.tsx
- packages/core/src/components/screens/settings/types.tsx
- packages/core/src/components/screens/settings/useLogout.ts
- packages/core/src/components/screens/settings/useSignOut.ts
- packages/core/src/hooks/index.ts
- packages/core/src/hooks/useAccountOrDemoAccount.ts
- packages/core/src/index.ts
- packages/core/src/store/mad-config/hooks.ts
- packages/core/src/types.ts
- packages/core/src/utils/createMadCoreNavigator.tsx
- packages/core/src/utils/getFinalSettingsConfig.ts
- packages/core/src/utils/getPremadeSettings.ts
- packages/core/tsconfig.json
This PR implements Settings Screen into mad-core
> feat: settings screen

- .changeset/purple-cars-clean.md
- packages/navigation/src/_internal/createMadDescriptors.ts
- packages/navigation/src/_internal/getCustomRenderFunction.tsx
Chronicles should work again after this fix
> fix: bug leading to mad-navigation not working

- .changeset/many-dolls-think.md
- .github/workflows/lint-pr.yml
- .vscode/settings.json
- apps/chronicles/app.json
- apps/chronicles/mad.config.ts
- apps/chronicles/package.json
- package.json
- packages/core/src/store/mad-config/hooks.ts
- packages/core/src/types.ts
- packages/core/src/utils/getRedirectUriFromAuthConfig.ts
- pnpm-lock.yaml
- turbo.json
- Created a completely fresh lockfile. This fixed web issues related to react-navigation.
- Changed react-native-msal version to newest commit. This was required in order to run `build:all`
- Added `web:chronicles` script for running the app for web
- Added `redirectUriWeb` in `MadConfig`. `mad-core` will automatically pick the correct redirectUri.
- Changed Chronicles' bundler to Metro.
~Note: There are still issues with web. Authentication does not work (#296) and WhatsNew screen seems to fail in demo mode (#297)~ Both of these issues were fixed when I changed to the Metro bundler
> feat: web support for chronicles

- .changeset/clever-planets-tell.md
- packages/core/src/components/screens/release-notes/ChangeLog.tsx
- packages/core/src/components/screens/release-notes/ReleaseNotesScreen.tsx
- packages/core/src/components/screens/release-notes/WhatsNewScreen.tsx
- packages/core/src/components/screens/release-notes/fetchReleaseNotes.ts
- packages/core/src/hooks/UseReleaseNotes.tsx
> feat: ReleaseNotesScreen.tsx

- .changeset/light-moose-sit.md
- packages/core/src/components/screens/LoginScreen.tsx
- packages/core/src/components/screens/release-notes/ReleaseNotesScreen.tsx
- packages/core/src/components/screens/release-notes/WhatsNewScreen.tsx
- packages/core/src/components/screens/settings/SettingsScreen.tsx
- packages/core/src/hooks/useScreenTitleFromDictionary.ts
- packages/core/src/language/en.json
- packages/core/src/language/nb.json
- packages/core/src/language/types.ts
- packages/core/src/language/useDictionary.ts
- packages/core/src/store/mad-config/hooks.ts
- packages/core/src/utils/createMadCoreNavigator.tsx
- packages/core/src/utils/getPremadeSettings.ts
Supports english and norwegian
> feat: dictionary support to core screens

- .changeset/orange-olives-walk.md
- apps/chronicles/app.json
- apps/chronicles/mad.config.ts
- apps/chronicles/settings.ts
- packages/core/src/components/screens/AboutScreen.tsx
- packages/core/src/store/mad-config/hooks.ts
> feat: Add `AboutScreen`

- .changeset/slow-ducks-speak.md
- packages/components/src/components/ProgressIndicator/useNoProgressAnimation.ts
Adjusted the circular progress animation so that it works properly on both web and device 
Fixes: #299
> fix(circularprogess): adjust spinner for web

- .changeset/shiny-fans-allow.md
- apps/chronicles/screens/components/components/CellScreen.tsx
- packages/components/src/components/Cell/Cell.tsx
Add `additionalSurface` prop to `Cell` component. 
Add `AdditionalSurfaceProps` type.
This prop type has `component` and `onPress` support.
> feat: Add additional touchable surface to `Cell` component

- .github/ISSUE_TEMPLATE/feature-form.yml
> chore: Update feature-form.yml

- .github/ISSUE_TEMPLATE/bug-form.yml
> chore: Update bug-form.yml

- .changeset/lemon-readers-battle.md
- apps/chronicles/screens/dfw/DFWDiscoverScreen.tsx
- apps/chronicles/screens/dfw/dfwcomponents/WorkOrderCellScreen.tsx
- apps/chronicles/types/dfwcomponents.ts
- packages/components/src/styling/masterToken.ts
- packages/components/src/styling/types.ts
- packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCell.tsx
- packages/dfw/src/dfwcomponents/WorkOrderCell/index.ts
- packages/dfw/src/index.ts
create component `WorkOrderCell`
create `WorkOrderCellScreen`
add navigation for `WorkOrderCellScreen`
> feat: create component `WorkOrderCell`

- .changeset/long-camels-compete.md
- packages/components/src/components/Cell/CellGroup.tsx
Removed unwanted bottom padding when title is not in use in Cell.Group
Fixes: #364
> fix(cellgroup): remove bottompadding when title is not in use

- .changeset/sweet-balloons-impress.md
> chore(components): add changeset for search

- .changeset/old-seas-hope.md
- packages/components/src/components/Menu/Menu.tsx
> fix: remove update `useEffect` from `Menu` component

- .changeset/fluffy-apples-melt.md
- .changeset/khaki-swans-scream.md
- apps/chronicles/screens/DrawScreen.tsx
- packages/skia-draw/src/hooks/useCanvasControl.ts
- packages/skia-draw/src/premades/ImageMarkup/EDSControlPanel/EDSControlPanel.tsx
- packages/skia-draw/src/premades/ImageMarkup/EDSControlPanel/TextInputBubble.tsx
- packages/skia-draw/src/premades/ImageMarkup/ImageMarkup.tsx
- Add keyboard avoidance functionality to image canvas text box
- Update default font size on text added to the image canvas component from 16 to 18
> feat: add keyboard avoidance to ImageCanvas text box

- .changeset/great-laws-argue.md
- apps/chronicles/screens/components/DiscoverScreen.tsx
- apps/chronicles/screens/components/components/SelectMenuScreen.tsx
- apps/chronicles/types/components.ts
- packages/components/src/components/SelectMenu/MultiselectMenu.tsx
- packages/components/src/components/SelectMenu/SelectMenu.tsx
- packages/components/src/components/SelectMenu/index.ts
- packages/components/src/components/SelectMenu/selectMenuStyles.ts
- packages/components/src/components/SelectMenu/types.ts
- packages/components/src/index.ts
- packages/components/src/styling/masterToken.ts
Create two new component SelectMenu and SelectMenu.Multiselect
- Created components:
- SelectMenu: Allows you to select and deselect single values from a list.
- SelectMenu.Multiselect: Allows you to select and deselect mulitiple values from a list.
- Fixed bug in dark theme where the text color on selected items was hard to see.
Fixes: #359 , #288
> feat(components): create selectmenu and multiselectmenu

- .changeset/fair-needles-wait.md
- packages/components/src/components/Cell/Cell.tsx
Did some minor styling adjustments to Cell.
- Added margin to the additional surface line.
- Centered the right adornment with the cell content
Fixes: #432
> style(cell): adjust styling

- .changeset/empty-ways-tell.md
- packages/components/src/components/Cell/Cell.tsx
Streched out the pressable surface in additional surface in the cell component
> fix(cell): strech out the pressable surface in additional surface

- .changeset/twelve-flowers-thank.md
- packages/components/src/components/Cell/Cell.tsx
Disabeling the cell onPress when swiping is happening
> fix: disable onpress when swiping

- .changeset/cuddly-geckos-walk.md
- .changeset/metal-candles-design.md
- apps/docs/docs/components/api/2-inputs/Button.mdx
- apps/docs/docs/components/api/4-feedback/Progress.mdx
- packages/components/src/components/SelectMenu/MultiselectMenu.tsx
- packages/components/src/components/SelectMenu/SelectMenu.tsx
- packages/components/src/components/SelectMenu/index.ts
- Add exports for prop types to SelectMenu and MultiselectMenu
- Add type exports to SelectMenu index file
- Add `Progress` component to docs
- Add `Button.Icon` component prop table to docs
> fix(components): export SelectMenu and SelectMenu.Multiselect  props

- .changeset/red-buses-carry.md
- packages/components/.eslintrc.cjs
- packages/components/__tests__/Typography.spec.tsx
- packages/components/babel.config.cjs
- packages/components/jest-setup.ts
- packages/components/jest.config.cjs
- packages/components/package.json
- packages/components/src/components/Typography/Typography.tsx
> fix(Typography): forward ref to inner text element

- packages/components/__tests__/Button.spec.tsx
- packages/components/__tests__/helloWorld.spec.ts
This PR adds basic tests for the Button component. It can be used as inspiration for future tests
> chore: add basic tests for button

- .changeset/hungry-frogs-hide.md
- packages/core/src/components/screens/AboutScreen.tsx
- packages/core/src/store/mad-config/hooks.ts
> feat(core): display authentication method in about screen

- .changeset/rare-seas-ring.md
- apps/chronicles/mad.config.ts
- packages/auth/package.json
- packages/auth/src/Expo-AuthSession/hooks/useAccount.ts
- packages/core/package.json
- packages/core/src/components/screens/AboutScreen.tsx
- packages/core/src/components/screens/LoginScreen.tsx
- packages/core/src/components/screens/release-notes/fetchReleaseNotes.ts
- packages/core/src/hooks/useAccountOrDemoAccount.ts
- packages/core/src/index.ts
- packages/core/src/types.ts
- yarn.lock
Fixes issues experienced when installing mad-core v.0.7.0 in a project. Primarily related to package dependency issue, and sets experimental as a an optional field.
> fix: many fixes, package dependencies, type safety

- .changeset/six-ties-whisper.md
- packages/skia-draw/package.json
Update `@shopify/react-native-skia` to newest version.
> chore: update package

- .changeset/fresh-seals-remember.md
- packages/components/src/components/Search/Search.tsx
Fixed onChange issues on the `Search` component.
Fixes: #531
> fix(search): fix onchange issues with search

- .changeset/wet-llamas-type.md
- packages/auth/src/Expo-AuthSession/authenticationHandler/auth.ts
this is to follow best practices
> fix: decode id token instead of access token

- .changeset/fifty-nails-agree.md
- .changeset/proud-cheetahs-tap.md
- .changeset/rare-actors-film.md
- apps/chronicles/hooks/useProgressUpload.ts
- apps/chronicles/screens/components/components/ProgressScreen.tsx
- packages/components/src/components/Progress/ProgressItem.tsx
- packages/components/src/components/Progress/ProgressItemStatus.tsx
- packages/components/src/components/Progress/ProgressStatusLine.tsx
- packages/components/src/components/Progress/ProgressTaskItem.tsx
- packages/components/src/components/Progress/progressUtils.ts
- packages/components/src/components/Progress/types.ts
***Key Changes:***
- Added `removed` status 
- Adjusted `Retry` and `Copy` button position. 
- Added animation to the progress status line.
> feat(progress): add removed status and progress status line animation 

- .changeset/silly-geese-occur.md
- packages/components/src/components/Cell/ButtonCell.tsx
- Add forward ref to ButtonCell
- Write changeset
> feat(components): add forward ref to ButtonCell component

- apps/chronicles/package.json
- yarn.lock
- re-lock repo
- add `-f` flag to ios xcode local env file deletion as part of Chronicles build step
> fix: fix edge case where build script failed

- .github/workflows/deploy-docs.yml
- .github/workflows/lint-pr.yml
- .github/workflows/release.yml
- yarn.lock
if this does not work, maybe yarn is not the best option....
> chore(workflow agents): set macos-latest as workflow agents

- .changeset/giant-cycles-carry.md
- .changeset/ten-clouds-refuse.md
- packages/components/src/components/Progress/ProgressExpandableSection.tsx
- packages/components/src/components/Search/Search.tsx
**key changes**
- Updated animations for the `Search` and `Progress` components to prevent unwanted behaviour.
Fixes: #585
> fix: fix search and progress animations

- .changeset/cold-hats-repeat.md
- package.json
- packages/api/maintenance-api/package.json
- packages/api/maintenance-api/src/lib/generated/core/ApiError.ts
- packages/api/maintenance-api/src/lib/generated/core/ApiRequestOptions.ts
- packages/api/maintenance-api/src/lib/generated/core/ApiResult.ts
- packages/api/maintenance-api/src/lib/generated/core/CancelablePromise.ts
- packages/api/maintenance-api/src/lib/generated/core/OpenAPI.ts
- packages/api/maintenance-api/src/lib/generated/core/request.ts
- packages/api/maintenance-api/src/lib/generated/index.ts
- packages/api/maintenance-api/src/lib/generated/services/ModifiedEndpointsService.ts
- yarn.lock
- move to using the fetch API client (was axios)
- remove old dependencies
- try fixing the redirect issue where authorization headers are not included under redirects
closes #601, closes #600
> feat(maintenance-api): switch to fetch client

- .changeset/itchy-eels-add.md
- packages/toast/src/ToastEmitter.tsx
- packages/toast/src/addToast.ts
- packages/toast/src/queue.ts
- move to `useSyncExternalStore` for queue system
closes #604
> fix(toast): fix error where toasts could be locked for eternity

- .changeset/cuddly-timers-fetch.md
- .changeset/funny-garlics-juggle.md
- .changeset/old-mangos-talk.md
- .changeset/purple-pugs-press.md
- apps/chronicles/screens/dfw/dfwcomponents/WorkOrderCellScreen.tsx
- packages/dfw/src/dfwcomponents/WorkOrderCell/PropertyList.tsx
- packages/dfw/src/dfwcomponents/WorkOrderCell/StatusIcon.tsx
- packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCell.tsx
- packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCellNavigation.tsx
- packages/dfw/src/dfwcomponents/WorkOrderCell/index.ts
- packages/dfw/src/dfwcomponents/WorkOrderCell/types.ts
- packages/dfw/src/dfwcomponents/WorkOrderCell/utils.ts
- Created new component `WorkOrderCell.Navigation`
- Updated showSymbols props: status icons can now be shown in both row and column
- Updated some of the text in the default labels
- Added new prop, overwriteLabel where you can overwrite the default labels
- Added possibility to overwrite the style on the Cell itself, for example the border width.
Fixes: #613
> fix(workordercell): improved component and  fixed deviations

- .changeset/strong-seals-rescue.md
- packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCell.tsx
Buttons should now be displayed correctly.
Fixes: #636
> fix(workordercell): fix visibility issues on buttons

- .changeset/stale-buttons-lay.md
- .changeset/two-pumas-trade.md
- apps/chronicles/screens/dfw/dfwcomponents/WorkOrderCellScreen.tsx
- packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderPropertyList.tsx
- packages/dfw/src/dfwcomponents/WorkOrderCell/utils.ts
- The validation for showing the start job button was incorrect and should not be shown as intended.
- Made the text in the cell selectable
> fix(workordercell): fix validation for the not started icon

- .changeset/long-weeks-attack.md
- packages/core/src/components/screens/create-incident/CreateIncidentScreen.tsx
> fix: make ticket number copyable

- .changeset/nasty-islands-care.md
- apps/chronicles/screens/dfw/dfwcomponents/WorkOrderCellScreen.tsx
- packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderPropertyList.tsx
- packages/dfw/src/dfwcomponents/WorkOrderCell/types.ts
> chore: Add main work center to WorkOrderCell

- .changeset/odd-feet-confess.md
- packages/components/src/components/Search/Search.tsx
> fix: fix search appearance on web
