equinor/mad

.changeset/plenty-chairs-sip.md, .changeset/slimy-bananas-warn.md, apps/chronicles/screens/components/TextFieldScreen.tsx, packages/components/src/components/Input/Input.tsx, packages/components/src/components/TextField/TextField.tsx, packages/components/src/styling/masterToken.ts, packages/components/src/styling/types.ts
- Adjust `Input` bottom border color
- Visually indicate focus state of `Input`
- Add `unit` prop to `TextField`
=> feat: text field unit

.changeset/fluffy-mayflies-visit.md, apps/chronicles/navigation/index.tsx, apps/chronicles/types.tsx, packages/components/src/components/Cell/Cell.tsx, packages/skia-draw/src/Canvas.tsx
- Add `forwardRef` to `Cell` component
- Fix console error regarding duplicate screen names (Discovery Tab and Discovery Stack)
- Minor clean-up of unused imports / formatting
closes #100
=> feat: add forwardRef support to cell

.changeset/eighty-shrimps-march.md, packages/components/src/components/Button/Button.tsx
=> fix: outlined button should now have the same height as other buttons

.github/ISSUE_TEMPLATE/bug-form.yml, .github/ISSUE_TEMPLATE/feature-form.yml
- Replace old form titles with `[TITLE]` (the user has to delete this as GitHub does not allow for emtpy titles in forms)
- Add "code snippets" to "Other" sections of the forms
closes #156
=> docs(repo): add code snippet placeholder text in issue form

.changeset/green-crabs-march.md, apps/chronicles/navigation/index.tsx, apps/chronicles/screens/DiscoverScreen.tsx, apps/chronicles/screens/components/SwitchCellScreen.tsx, packages/components/src/components/Cell/SwitchCell.tsx, packages/components/src/components/Cell/index.ts, packages/components/src/components/Switch/Switch.tsx
Added a new component `Cell.Switch` based on previous child cell components. It takes the same props as both switch and cell. 
Added `SwitchCellScreen` to display different prop usage and functionality. 
Added navigation for `SwitchCellScreen`.
Removed unused code from `Switch` component.
=> feat: add `Cell.Switch` component

.changeset/fast-sloths-rhyme.md, apps/chronicles/screens/components/CellScreen.tsx, packages/components/src/components/Cell/Cell.tsx
- Remove full flex in `Cell` content container styling
=> fix: `Cell` styling not working correctly outside of scroll views

.changeset/giant-wombats-cough.md, packages/components/src/components/Accordion/AccordionItem.tsx, packages/components/src/components/Cell/ButtonCell.tsx, packages/components/src/components/Cell/Cell.tsx, packages/components/src/components/Cell/CellGroup.tsx, packages/components/src/components/Cell/SwitchCell.tsx
- Add inner wrapper child view in `Cell` children container
- Remove flex misuse in `Cell.Button`, `Cell.Switch`, `Cell.Group` `Accordion.Item`
=> fix: accordion item chevron not showing properly

.changeset/fuzzy-goats-admire.md, packages/components/src/components/Button/IconButton.tsx
Pressable container size was incorrect
- Changed the size on the pressable container around the icon button to it's correct size
=> fix(iconbutton): Adjust pressable container size on icon button

.changeset/shaggy-berries-join.md, apps/chronicles/package.json, apps/chronicles/screens/LoginScreen.tsx, packages/auth/src/components/LoginButton.tsx, packages/auth/src/hooks/useAuthenticate.ts
Dont know if this will help with our login issues, but it shouldn't make things worse!
I've sent an admin request consent for mad api prod, so we will have to check on monday if it makes things better.
This feature adds the ability to add scopes to the loginbutton. If you don't use the new prop, the scopes will be an empty array by default
=> feat: add scopes prop to login button

apps/chronicles/package.json, packages/auth/package.json, packages/auth/tsup.config.ts, packages/components/package.json, packages/components/src/utils/getBackgroundColorForButton.ts, packages/components/tsup.config.ts, packages/insights/package.json, packages/insights/tsup.config.ts, packages/navigation/package.json, packages/navigation/tsup.config.ts, packages/skia-draw/package.json, packages/skia-draw/tsup.config.ts
Fixed by changing back to tsc for compiling declaration files.
- In watch mode, we run `tsc` as part of tsup, in the onSuccess function
- When we run `build` (which is not in watch mode), we run tsc after tsup is finished, to make sure the step throws an error if it fails
=> chore: fix PR validation

.changeset/wicked-carrots-kick.md, packages/components/src/components/Typography/Typography.tsx
Adds support for nesting Typography components and other JSX elements. Tested it a bit in Code of Conduct and seems to handle most props with ease (e.g. View, TouchableOpacity etc.)
=> fix: add JSX Elements to child props of Typography

.changeset/afraid-crabs-camp.md, packages/components/src/components/ProgressIndicator/LinearProgress.tsx
- Remove `flex: 1`
Closes #286
=> fix(components): `LinearProgress` takes up too much vertical space

.changeset/healthy-nails-unite.md, apps/chronicles/hooks/useCachedResources.ts, packages/components/src/hooks/useEDS.ts
- Stop loading unused font in chronicles.
- Start loading `MaterialCommunityIcons` in `useEDS`.
Closes #277
=> perf: load `MaterialCommunityIcons` font in `useEDS`

.changeset/thick-fireants-melt.md, packages/components/src/components/Button/Button.tsx, packages/components/src/components/Button/index.ts
- Remove wrapper `View` to make the `style` prop on `Button` behave as expected.
- Add `ButtonSpecificProps` type which has the same types as `ButtonProps` had.
- Update `ButtonProps` type to be `ButtonSpecificProps`  and `ViewProps`.
Closes #170
=> fix(button): pass `style` prop to outermost component

.changeset/lovely-parents-work.md, .changeset/two-ads-obey.md, apps/chronicles/screens/components/ComponentScreen.tsx, apps/chronicles/screens/components/components/InputScreen.tsx, apps/chronicles/settings.ts, package.json, packages/components/.eslintrc.cjs, packages/components/src/components/Dialog/service/DialogServiceProvider.tsx, packages/components/src/components/EDSProvider/EDSProvider.tsx, packages/components/src/components/Input/Input.tsx, packages/components/src/components/Input/InputStyle.ts, packages/components/src/components/Portal/index.ts, packages/components/src/components/Search/Search.tsx, packages/components/tsconfig.json, packages/core/src/components/screens/create-incident/CreateIncidentScreen.tsx, pnpm-lock.yaml
- add `readOnly` prop to `Input` component
- add example to Chronicles
- refactor `Input` component styling
- add path aliases to mad components
- fix some cyclic deps issues in components
=> feat!: add `readOnly` prop to `Input` component

.changeset/calm-bears-look.md, packages/components/src/components/Tabs/Tabs.tsx
- Rollback `RenderCurrentTabChild` to version prior to release 0.9.0 in mad components
=> fix: rollback tabs render function

.changeset/curly-doors-film.md, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCell.tsx
Add check if `PropertyRow` value is truthy, if it is not, dont render component.
=> fix: add check to `WorkOrderCell` if value is truthy

.changeset/rotten-actors-raise.md, packages/components/src/components/Menu/Menu.tsx
Add update function from Floating UI to a useEffect that listens to children of `Menu`.
=> fix: menu doesnt rerender when children change

.changeset/happy-rocks-agree.md, packages/components/src/components/Search/Search.tsx
Corrected the flex layout on search.
Made the cancel button hidden / non interactive when the cancel button is not showing.
=> fix(search): adjusted flex and cancel button

.changeset/wild-shrimps-juggle.md, packages/components/src/components/Search/Search.tsx
Adjusted the animation on `Search` so that it looks correctly when the cancel button is appearing.
Removed unused styling.
=> fix(search): adjust animation on cancel button

.changeset/cuddly-berries-travel.md, packages/components/src/components/Search/Search.tsx
Minor flex adjustments on Search. This prevents adjacent elements to search to go out off the screen.
=> fix(search): adjust flex

.changeset/nice-bugs-tell.md, packages/components/src/components/Search/Search.tsx
Adjusted styling on Search to prevent that it collapses in some cases
=> fix(search): prevent search to collapse

.changeset/config.json, .changeset/two-owls-pull.md, .github/workflows/deploy-docs.yml, .github/workflows/release.yml
- De-ignore docs package from changesets (it is still ignored for npmjs publishing)
- Create docs deploy workflow
- Create initial changeset
=> build(docs): create `docs-deploy` workflow for deploying docs page

.changeset/hungry-points-train.md, packages/core/package.json, packages/core/src/components/screens/release-notes/ChangeLog.tsx, pnpm-lock.yaml
Fix issue related to docusaurus and react-native-render-html requiring different versions of "entities" by migrating to react-native-markdown-display package. also eliminates the need for "showdown"
=> fix(core): package mismatch between docusaurus and react native render html

.changeset/tasty-planets-dance.md, packages/components/src/styling/colors.ts, packages/components/src/styling/masterToken.ts
Active chip had a issue where the background color and text color was the same.
Correct the text and background color in dark mode for chip and menu. 
- Added new color, `interactive_primary_dark_selected_highlight`
- Updated the color for text - menu - active - dark. 
It now looks like this:
Fixes: #343
=> fix: correct color in dark mode for chip and menu

.github/workflows/lint-pr.yml
Adds temporary workaround to the concurrency issue plagueing the Code Validator github action.
Longterm fix is probably to migrate to Yarn Modern
ref: https://github.com/yarnpkg/yarn/issues/7212
=> fix(actions): Update lint-pr.yml

.changeset/happy-starfishes-greet.md, packages/components/src/components/Select/Multiselect.tsx, packages/components/src/components/Select/Select.tsx
Prevent Select and MultiSelect to from "collapsing" when using flex direction row.
Fixes: #506
=> fix(select): make select and multiselect responsive

.changeset/poor-penguins-applaud.md, packages/components/src/components/Input/inputStyle.ts
Corrected the text color in the`Input` component, which is being used in both `TextField` and `Search`. This should now work fine in both light and dark mode.
Fixes: #517
=> fix(input): add color to input

.changeset/little-kids-tan.md, .changeset/tame-owls-sniff.md, .changeset/young-beds-own.md, apps/chronicles/hooks/useProgressUpload.ts, apps/chronicles/navigation/index.tsx, apps/chronicles/screens/components/components/ProgressScreen.tsx, packages/components/src/components/Progress/ProgressExpandButton.tsx, packages/components/src/components/Progress/ProgressItem.tsx, packages/components/src/components/Progress/ProgressItemStatus.tsx, packages/components/src/components/Progress/ProgressTaskItem.tsx
- Change Typography and spacing for progress items
- Dynamically style progress item task lines based on task status
- Switch expand `Button` for `Button.Icon` on smaller screens to give more room for progress item title
- Restructure `ProgressItem` component layout to accomodate for more space available in task container
- Add dog example progress to `ProgressScreen` in Chronicles
- Remove margin in settings button in Chronicles
closes #543
=> feat(Progress): Touch up `Progress` component

.changeset/metal-parents-live.md, .changeset/rich-countries-drop.md, apps/chronicles/hooks/useProgressUpload.ts, packages/components/src/components/Progress/ProgressExpandableSection.tsx, packages/components/src/components/Progress/ProgressItem.tsx, packages/components/src/components/Progress/ProgressTaskItem.tsx, packages/components/src/components/Progress/types.ts
***Key changes:***
- Fixed issue where tasks with removed status was not included in the task counter in the `Progress`
component
- Added new `icon` and `iconColor` props, allowing users to display an icon on the right side of the
=> feat(progress): add icon to progress tasks

.changeset/good-pugs-repeat.md, packages/core/src/components/screens/create-incident/CreateIncidentScreen.tsx
If you select any input field in the feedback menu then you should now be able to scroll to the bottom of the page while also seeing the keyboard.
=> fix: Keyboard covering input fields in the feedback screen

.changeset/thirty-papayas-cry.md, packages/dfw/src/dfwcomponents/PropertyRow/PropertyRow.tsx
Adds a selectable prop to the PropertyRow component. This makes the value property selectable on iOS.
=> fix: Add selectable prop to PropertyRow

.changeset/cool-pans-remain.md, apps/chronicles/screens/DrawScreen.tsx, packages/skia-draw/src/CanvasControlProvider/types.ts, packages/skia-draw/src/hooks/useDrawHandle.ts, packages/skia-draw/src/premades/ImageMarkup/ImageMarkup.tsx, packages/skia-draw/src/premades/SignaturePad/SignaturePad.tsx, packages/skia-draw/src/types.ts
- Add `encodingOptions` parameter to `makeImageSnapshot` method
- Add `data` field in `makeImageSnapshot` method that only contains base64 image data
closes #595
=> feat(skia): add image encoding options to makeImageSnapshot

.changeset/slow-teachers-sneeze.md, apps/chronicles/hooks/useProgressUpload.ts, apps/chronicles/screens/components/components/ProgressScreen.tsx, packages/components/__tests__/Cell.spec.tsx, packages/components/src/components/Progress/ProgressItem.tsx, packages/components/src/components/Progress/ProgressTaskItem.tsx, packages/components/src/components/Progress/__tests__/progressUtils.spec.ts, packages/components/src/components/Progress/progressUtils.ts, packages/components/src/components/Progress/types.ts
- Fix issue where items that have tasks containing only `success` and `notStarted` were summarized as
- Write unit tests for `summarizeStatuses`
- Remove `removed` status
=> feat(progress)!: remove `removed` status on progress item and decendants

.changeset/four-owls-bow.md, .changeset/giant-clouds-bow.md, packages/components/src/components/Cell/Cell.tsx, packages/components/src/components/PressableHighlight/PressableHighlight.tsx
- Replaced `PressableHighlight` with `TouchableWithoutFeedback` when the cell is swipable
- Fixed bug where the divider in Cell.Group was cropped if you have a cell with `additionalSurface` prop.
Fixes: #607
=> fix(cell): use gesture handler when the cell i swipeable

.changeset/tame-melons-hunt.md, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCell.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/types.ts
Added loading prop to buttons (Start job, Teco and ready for operation)
Fixes: #619
=> fix(WorkOrderCell): added loading prop to buttons

.changeset/tricky-deers-argue.md, apps/chronicles/screens/dfw/dfwcomponents/WorkOrderCellScreen.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/PropertyList.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCell.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCellNavigation.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/index.ts, packages/dfw/src/dfwcomponents/WorkOrderCell/types.ts, packages/dfw/src/dfwcomponents/WorkOrderCell/utils.ts
***Key changes:***
- Replaced moment with Date.
- Removed the `Ready for execution` icon and label. 
- If the status do not include STRT it should show a new label and icon.
- Simplified the component, remove unnecessary props and logic.
- Renamed the workOrder prop to workOrderId.
- Add new prop, workOrderType.
- remove the symbolDirection prop. Symbols should only be displayed in column.
Fixes: #622
=> fix(workordercell): improve component and fix deviations

.changeset/tough-days-drum.md, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCell.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCellNavigation.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/types.ts
- Added new value to the `WorkOrderType`, "unkown". 
- Fix padding issue for when the `maintenanceType` is not being used.
Fixes: #625
=> fix(workordercell): remove excess padding and add work order type

.changeset/afraid-peaches-jam.md, .changeset/kind-buckets-accept.md, .changeset/sour-forks-clap.md, apps/chronicles/screens/dfw/dfwcomponents/WorkOrderCellScreen.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCell.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCellNavigation.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderPropertyList.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/types.ts
- Make the `WorkOrderCell.Navigation` swipeable.
- Changed label `Functional Location` to `Functional location` and adjusted its position in the property list. According to Figma, it should be placed further down.
https://www.figma.com/design/S4NQWezdYGuVz5aAp4xAo4Bl/WorkOrders?node-id=29970-74977&node-type=canvas&t=7zBMgCSo3bSXpvLu-0 
- Added new value, `Operations from filter`,  to the `WorkOrderPropertyList`.
Fixes: #631
=> feat(workordercell): make the navigation variant swipeable

.changeset/dry-rivers-begin.md, packages/dfw/src/dfwcomponents/WorkOrderCell/utils.ts
Changed the finished icon in the `WorkOrderCell` from `circle` to `check-circle`
=> fix(workordercell): change the finish icon

.changeset/afraid-horses-drop.md, packages/dfw/src/dfwcomponents/PropertyRow/PropertyRow.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCell.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCellNavigation.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderPropertyList.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/types.ts
New prop, `wrapValues` that make text values wrap in the WorkOrderCell and WorkOrderCell.Navigation.
Aslo found and removed a {" "} in the WorkOrderCell.Navigation that made the app crash on IoS.
Fixes: #648
=> fix(workordercell): make text values wrap

.changeset/spotty-poets-melt.md, apps/chronicles/screens/dfw/dfwcomponents/WorkOrderCellScreen.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCellNavigation.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/utils.ts
- Added a new bookmarked prop to the WorkOrderCell.Navigation component, which can be used to indicate whether the work order is bookmarked or not. Additionally, new icons have been included to reflect the bookmarked state.
Fixes: #653
=> feat(workordercell): add bookmark icons to the navigation variant

.changeset/unlucky-phones-smash.md, packages/toast/src/components/ToastComponent.tsx
In some cases we are unable to display the entire toast message using two lines. This PR increases the maximum to 4 lines.
=> chore: set max 4 lines of text in toasts

.changeset/modern-feet-unite.md, apps/chronicles/screens/dfw/dfwcomponents/WorkOrderCellScreen.tsx, packages/dfw/src/dfwcomponents/WorkOrderCell/WorkOrderCellNavigation.tsx
Icons now shows on a new line on smaller devices in the WorkOrderCell.Navigation component. 
Note, this only happens on smaller devices, such as phones. On tablets the show as before.
Fixes: #659
=> fix(workordercell): make icons wrap on smaller devices

.changeset/nine-spiders-tan.md, packages/api/maintenance-api/src/lib/generated/models/WorkOrderOperationInPlan.ts
Adds a missing type to the wrapper.
=> chore: Update wrapper

.changeset/silly-coats-end.md, apps/chronicles/screens/components/components/ButtonScreen.tsx, packages/components/src/components/Button/IconButton.tsx
Added new prop, `busy`, in the `Button.Icon` component. When true it shows a loading indicator.
Fixes: #477
=> feat(button): add loading indicator in the icon button

.changeset/cold-mice-doubt.md, apps/chronicles/screens/components/components/ButtonScreen.tsx, packages/components/src/components/Button/Button.tsx
Added fullwidth prop to the button component 
Fixes: #164
=> feat(Button): add new prop fullwidth

.changeset/cuddly-carpets-attack.md, .changeset/empty-crews-serve.md, packages/components/src/components/Cell/index.ts, packages/core/src/components/service-message/ServiceMessageBanner.tsx, packages/core/src/components/service-message/components/SwipeItem.tsx
Also, we no longer export `CellSwipeItem` from `mad-components`
=> fix(core): remove-button on service message banner now works again

.changeset/small-tables-work.md, .changeset/thin-rice-sort.md, apps/chronicles/navigation/index.tsx, apps/chronicles/package.json, apps/docs/docs/mad-core/migration-guide/3-use-createCoreStackNavigator.md, apps/docs/docs/mad-core/migration-guide/4-replace-navigation-imports.md, apps/docs/docs/mad-navigation/2-installation.md, apps/docs/docs/mad-navigation/3-usage.md, packages/core/src/components/CoreNavigatorTypeProvider.tsx, packages/core/src/components/createCoreStackNavigator.tsx, packages/core/src/components/navigation/navigation-creators.ts, packages/core/src/components/screens/AboutScreen.tsx, packages/core/src/store/mad-config/mad-config.ts, packages/core/src/utils/MadCoreProviders.tsx, packages/core/src/utils/createMadCoreNavigator.tsx, packages/core/src/utils/getDefaultScreenOptionsForLoginScreen.tsx, packages/navigation/package.json, packages/navigation/src/index.ts, packages/navigation/src/stack/createStackNavigator.tsx, packages/navigation/src/stack/index.ts, packages/navigation/src/stack/types.ts, yarn.lock
This PR adds stack navigator support to `mad-navigation` and `mad-core`.
In `mad-core`, `createCoreStackNavigator` is deprecated and replaced with `createStackCoreNavigator` and `createNativeStackCoreNavigator`.
The stack type you choose is displayed in the about-screen.
Closes #693 and #692
=> feat(CORE/NAVIGATION): stack navigator support

.changeset/dirty-rockets-sin.md, packages/components/src/components/Search/Search.tsx
Add disabled prop to x icon so that it will not let user clear the search field when used
=> fix: add disabled prop to x icon

.changeset/mighty-readers-film.md, .changeset/sharp-snails-guess.md, apps/chronicles/screens/components/components/ButtonScreen.tsx, packages/components/src/components/Button/Button.tsx, packages/components/src/components/Dialog/Dialog.tsx, packages/components/src/components/Dialog/DialogActions.tsx, packages/components/src/components/Dialog/DialogCustomContent.tsx, packages/components/src/components/Dialog/DialogHeader.tsx, packages/components/src/components/Scrim/Scrim.tsx, packages/components/src/components/_internal/PopInContainer.tsx
Components
- Make dialog title responsive
- Make dialog custom content scrollable
- Make action buttons wrap when necessary
- Avoid clipping of button content in dialog action buttons
Chronicles
- Wrap buttons in button screen
- Make gap and padding in button row responsive
Closes #711
=> fix: make dialog responsive
